### ISSUE TITLE
Redundant polyfills

### ISSUE THREAD

**Issue by trsh** [retejs/rete-cli#1]
Every plugin created with cli adds lot's of polyfills, so they repeat in project scope and create a large redundant boilerplate. 

We should exclude polyfills and project developers can add manually https://cdn.polyfill.io/v2/polyfill.js?features=Array.prototype.map,modernizr:es5array|always if needed.

**Comment by Ni55aN** [comment]
I think this isn't a large amount of memory. 
In any case, you can import and minify a `*.debug.js` bundles

**Comment by trsh** [comment]
> I think this isn't a large amount of memory.

But it's ~6kb. 5 plugins and 30 kb, whats is size of some complete library :/. What is 24 of redundant code.

**Comment by Ni55aN** [comment]
Can you try to minify *.debug.js bundles while building app?

**Comment by Ni55aN** [comment]
@trsh what build system are you using? (webpack, rollup, etc)

**Comment by trsh** [comment]
@Ni55aN i basically cloned vue rendering plugin from git! So is use same as there. United style :)))

**Comment by trsh** [comment]
@Ni55aN please check this https://medium.com/@addyosmani/the-cost-of-javascript-in-2018-7d8950fbb5d4 or google something better on the topic. Size does matter a lot for smooth experience. Nothing comes for free. If its tons of JS lines, js interpreter will need to process/compile on run-time. So it's kind of important to stay as small ass possible.

**Comment by Ni55aN** [comment]
@trsh I cannot reduce the size of the source code after minimization. If `/ src` takes 5 kb
and uses some resource loaders (sass, vue.js), the package size after minimization may take more than 5 kb (how loaders work).

Solution: chunks + lazy loading.

**Comment by trsh** [comment]
@Ni55aN yes, but the polyis are redundant :P. Lots of projects even don't support **not** modern browsers by default, so its lots ok KB for nothing. Going with debug js or npm and rolling own packer is not for everybody. But it's your choice, so im closing this.
